### ISSUE TITLE
Atom Progress Tracker 

### ISSUE THREAD

**Issue by AnomolyLove** [AnomolyPlugins/Atom#1]
# Atom Panel

- [ ] Create table for users
- [ ] Add permission group system
- [ ] Create page to view users requseting access to panel
- [ ]Add features to limit users to certain actions (Create a permission page)
- [ ]Display Permission file
- [ ]Add ban ability (add settings to use GlobalBan or AtomBan)
- [ ]Add theme customiablity. 
- [ ]Add User Preference settings

# Servers

- [ ]Add customizable commands to execute to server
- [ ]Add Quick Actions for Players
- [ ]Add Console view
- [ ]Add Online/Offline status to servers page

# Players
- [ ]View players that have access to panel
- [ ]View player stats (Recent players, play time, etc)
- [ ]Ability to purge player from database (Delete player file on server)
